Algoritmo "Questão2"
// Autor(a)    : Lucas Prates
// Data atual  : 27/09/2022

Var

cres,decre,n1:inteiro
result:real

Inicio

escreval("Digite um número que sejá maior que 0")
leia(n1)

se (n1>0) entao

   para cres de 1 ate n1 passo 1 faca



   fimpara


   para decre de n1 ate 1 passo 1 faca



   fimpara

   result <- cres/decre

   limpatela
   escreval("Número digitado: ",n1)
   escreval("Resultado: ",result)

fimse


Fimalgoritmo